# Generated by Django 5.1.6 on 2025-05-19 03:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nckh9', '0003_hocky'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rules',
        ),
        migrations.AlterModelOptions(
            name='hocky',
            options={'ordering': ['-nam_hoc', '-hoc_ky']},
        ),
        migrations.RenameField(
            model_name='hocky',
            old_name='he_dao_tao',
            new_name='ten_hoc_ky',
        ),
        migrations.AlterUniqueTogether(
            name='hocky',
            unique_together={('nam_hoc', 'hoc_ky')},
        ),
        migrations.RemoveField(
            model_name='studentsreport',
            name='mucKhieuNai',
        ),
        migrations.RemoveField(
            model_name='studentsreport',
            name='picture',
        ),
        migrations.AddField(
            model_name='hocky',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='hocky',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hocky',
            name='ma_hoc_ky',
            field=models.CharField(blank=True, default='HK_DEFAULT', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hocky',
            name='ngay_bat_dau',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AddField(
            model_name='hocky',
            name='ngay_bat_dau_danh_gia',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AddField(
            model_name='hocky',
            name='ngay_ket_thuc',
            field=models.DateField(default='2025-06-30'),
        ),
        migrations.AddField(
            model_name='hocky',
            name='ngay_ket_thuc_danh_gia',
            field=models.DateField(default='2025-06-30'),
        ),
        migrations.AddField(
            model_name='hocky',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentsreport',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='studentsreport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studentsreport',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='uploads/reports/'),
        ),
        migrations.AddField(
            model_name='studentsreport',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang chờ'), ('approved', 'Đã duyệt'), ('rejected', 'Đã từ chối')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='studentsreport',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_nckh9.infostudent'),
        ),
        migrations.AlterField(
            model_name='hocky',
            name='hoc_ky',
            field=models.IntegerField(choices=[(1, 'Học kỳ 1'), (2, 'Học kỳ 2')]),
        ),
        migrations.AlterField(
            model_name='studentsreport',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_nckh9.hocky'),
        ),
        migrations.AlterField(
            model_name='studentsreport',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='hocky',
            name='sinhvien',
        ),
    ]
