# Generated by Django 5.1.6 on 2025-05-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nckh9', '0006_sinhvientdg_trangthai'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyactive',
            name='maSV',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
