# Generated by Django 4.2.7 on 2025-05-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_nckh9", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsyncExportTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("excel", "Excel"), ("csv", "CSV")],
                        max_length=10,
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("scores", "Điểm số"),
                            ("appeals", "Khiếu nại"),
                            ("users", "Người dùng"),
                            ("activities", "Hoạt động"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Đang chờ"),
                            ("processing", "Đang xử lý"),
                            ("completed", "Hoàn thành"),
                            ("failed", "Thất bại"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("progress", models.IntegerField(default=0)),
                ("file_path", models.CharField(blank=True, max_length=255, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("include_fields", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AsyncSyncTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("full", "Đồng bộ toàn bộ"),
                            ("incremental", "Đồng bộ tăng dần"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_system", models.CharField(max_length=100)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("scores", "Điểm số"),
                            ("users", "Người dùng"),
                            ("activities", "Hoạt động"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Đang chờ"),
                            ("processing", "Đang xử lý"),
                            ("completed", "Hoàn thành"),
                            ("failed", "Thất bại"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("progress", models.IntegerField(default=0)),
                ("total_records", models.IntegerField(blank=True, null=True)),
                ("processed_records", models.IntegerField(default=0)),
                ("failed_records", models.IntegerField(default=0)),
                ("errors", models.JSONField(default=list)),
                ("last_sync_time", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
