# Generated by Django 5.1.6 on 2025-05-11 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nckh9', '0002_asyncexporttask_asyncsynctask'),
    ]

    operations = [
        migrations.CreateModel(
            name='HocKy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam_hoc', models.IntegerField()),
                ('hoc_ky', models.IntegerField()),
                ('he_dao_tao', models.CharField(max_length=255)),
                ('sinhvien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hocky', to='app_nckh9.infostudent')),
            ],
        ),
    ]
