# Generated by Django 5.1.6 on 2025-05-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nckh9', '0004_delete_rules_alter_hocky_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infostudent',
            name='khoaHoc',
            field=models.IntegerField(default=2023),
        ),
    ]
